[REV-330] 예외 처리시 헤더에 상태 코드를 넣도록 수정
prgrms-web-devcourse/Team-12-ReviewRanger-BE pull request #109
Opened 2023-11-25 16:48 UTC by beombu

### 👍 PR DESCRIPTION
- 예외 처리시에 헤더에 상태 코드를 넣도록 수정하였습니다.

### 🥺 TO REVIEWER  
- 최대한 기존 코드를 건드리지 않았습니다.
- 동기적으로 예외 정의랑 GlobalExceptionHandler 외 발생하는 예외를 핸들러로 옮기는 작업이 필요할 것 같습니다.

2023-11-25 16:51 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java
>  		String errorCode,
errorCode도 필요 없다고 생각합니다!

2023-11-25 16:51 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java
> +			throw new RangerException(NOT_CORRECT_JWT);
여기에 어떤 예외가 발생해야 하는지 몰라서 알려주시면 수정하겠습니다!

2023-11-25 17:51 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java
> +			throw new RangerException(NOT_CORRECT_JWT);
이거는 filter단에서 걸리는 예외라서 spring에서 정의한 커스텀 핸들러에 안 걸려요! 그래서 그대로 두셔도 될 것 같습니당.

2023-11-25 18:03 UTC, sujjangOvO requested changes
수고하셨습니다!! 덕분에 상태코드를 클라이언트에게 전달할 수 있게 되었네요 ㅎㅎㅎㅎ jwt 핸들러 부분만 다시 롤백해주시면 될 것 같습니다!!!!

2023-11-25 18:03 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java
> +	@ExceptionHandler(DataAccessException.class)
요거는 어디서 발생하는 예외인가용?

2023-11-25 23:06 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java
> +	@ExceptionHandler(DataAccessException.class)
모든 SQL 예외시 `DataAccessException`을 던집니다!

2023-11-25 23:11 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java
> +			throw new RangerException(NOT_CORRECT_JWT);
[b634925](https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-BE/pull/109/commits/b6349257e60520ea312d4a9e1119b088d432fedf)
롤백했습니다!

2023-11-25 23:11 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java
>  		String errorCode,
[b634925](https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-BE/pull/109/commits/b6349257e60520ea312d4a9e1119b088d432fedf)
추가 반영했습니다!

2023-11-25 23:29 UTC, JuwoongKim reviewed
수고하셨습니다!

2023-11-25 23:29 UTC, JuwoongKim approved these changes

2023-11-26 06:37 UTC, sujjangOvO approved these changes
수고하셨습니당 !!

2023-11-26 07:15 UTC, merged