[REV-121] 리뷰를 받은 수신자 전체 조회 기능 구현
prgrms-web-devcourse/Team-12-ReviewRanger-BE pull request #30
Opened 2023-11-02 18:50 UTC by beombu

### 👍 PR DESCRIPTION
- 리뷰를 받은 수신자 전체 조회 기능을 구현하였습니다.

### 🥺 TO REVIEWER  
- 쿼리문으로 구현하고 싶었지만 구현을 실패하여 Map을 통해 구현하였습니다.
- 비즈니스 로직에서 생각하신 로직이 있으시다면 조언 부탁드립니다.

2023-11-03 03:39 UTC, JuwoongKim reviewed
범철님 고생하셨습니다!!
비지니스 로직 부분에 대해 간단히 코멘트 남겼습니다!

2023-11-03 03:39 UTC, JuwoongKim commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java
> +			}
해당 부분이 어떤 것을 위해 필요한지 알 수 있을까요?? 
본인을 리뷰한 사람 횟수를 나타내기 위해 작성한 것 맞을까요??

2023-11-03 03:50 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java
> +			}
맞습니다! 응답자가 설문에 참여할때 마다 개별결과테이블이 리뷰 대상 갯수만큼 증가하기 때문에 리뷰 대상을 키로 가지고 그 횟수를 증가시켰습니다

2023-11-03 06:29 UTC, sujjangOvO requested changes
수고하셨슴니당! 좀 복잡한데 고생많으셨어여 ㅎㅎ

2023-11-03 06:29 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/response/api/ResponseRestController.java
> +		return RangerResponse.ok(responseService.createResponse(request));
변수 한 단계 빼서 적용하는건 어떠신가여!?

2023-11-03 06:29 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/AllRecipientParticipateInSurveyDto.java
> +) {
요거 dto안에 list 자료구조가 있으면 dto.recipient.get(index)로 좀 깊어지던데 Recipient list로만 가져가도 되지 않을까여?>? (진짜 궁금함)

2023-11-03 06:29 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java
> +			.orElseThrow(() -> new RangerException(NOT_FOUND_SURVEY));
👍

2023-11-03 06:29 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/Recipients.java
> +public record Recipients(
dto 네이밍에 복수형을 사용하신 이유가 무엇일까요??

2023-11-03 06:29 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/AllRecipientParticipateInSurveyDto.java
> +) {
그냥 `List<Recipient>` 이런 형태로! list만 들어있다면 json의 깊이도 깊어질 것 같아여!

2023-11-03 06:29 UTC, sujjangOvO commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java
> +				List<Long> responers = subjectToResponsersMap.getOrDefault(subjectId, new ArrayList<>());
new ArrayList를 선언하는 부분을 밖으로 빼는게 좀 더 가독성 좋지 않을까용??ㅠㅠ

2023-11-03 08:48 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/AllRecipientParticipateInSurveyDto.java
> +) {
프론트에게 응답값을 전달할 때 전체 Json(AllRecipientParticipateInSurveyDto) 안에 값을 넣어줘야 할 것 같아서 이렇게 만들었습니다!! 그냥 리스트로 보내도 상관없을까요??

2023-11-03 09:38 UTC, beombu commented on src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java
> +				List<Long> responers = subjectToResponsersMap.getOrDefault(subjectId, new ArrayList<>());
변수명 하나만 추천해주실 수 있나요?

2023-11-04 06:56 UTC, sujjangOvO approved these changes

2023-11-04 06:56 UTC, merged